{% set name = "bgen" %}
{% set version = "4.1.6" %}
{% set sha256 = "77b58c2df7eff69d5b8e8726e6fa7ddd95daca6df6635007919f32f46a25d27e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/bgen/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
  host:
    - almosthere >=2.0.2
    - conda-build
    - zlib  # [win]
    - zstd
  run:
    - almosthere >=2.0.2
    - zlib  # [win]
    - zstd

test:
  commands:
    - test -e $PREFIX/lib/libbgen.so                      # [linux]
    - test -e $PREFIX/lib/libbgen.dylib                   # [osx]
    - if NOT exist %LIBRARY_LIB%/bgen.lib exit 1          # [win]
    - if NOT exist %LIBRARY_BIN%/bgen.dll exit 1          # [win]
    - if NOT exist %LIBRARY_INC%/bgen/bgen.h exit 1       # [win]
    - if NOT exist %LIBRARY_INC%/bgen/bstring.h exit 1    # [win]
    - if NOT exist %LIBRARY_INC%/bgen/export.h exit 1     # [win]
    - if NOT exist %LIBRARY_INC%/bgen/file.h exit 1       # [win]
    - if NOT exist %LIBRARY_INC%/bgen/genotype.h exit 1   # [win]
    - if NOT exist %LIBRARY_INC%/bgen/metafile.h exit 1   # [win]
    - if NOT exist %LIBRARY_INC%/bgen/partition.h exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/bgen/samples.h exit 1    # [win]
    - if NOT exist %LIBRARY_INC%/bgen/variant.h exit 1    # [win]

about:
  home: https://github.com/limix/bgen
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A BGEN file format reader
  doc_url: https://bgen.readthedocs.io
  dev_url: https://github.com/limix/bgen

extra:
  recipe-maintainers:
    - horta
