{% set name = "bgen" %}
{% set version = "2.1.0" %}
{% set sha256 = "391be3c3439050a9833510cffe506c7634d5337c236aaa405494e3d157e9ab8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/bgen/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - almosthere >=1.0.3
    - conda-build
    - zlib  # [win]
    - zstd
  run:
    - almosthere >=1.0.3
    - zlib  # [win]
    - zstd

test:
  commands:
    - test -e $PREFIX/lib/libbgen.so                     # [linux]
    - test -e $PREFIX/lib/libbgen_static.a               # [unix]
    - test -e $PREFIX/include/bgen.h                     # [unix]
    - test -e $PREFIX/lib/libbgen.dylib                  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME        # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME         # [osx]
    - if NOT exist %LIBRARY_LIB%/bgen.lib exit 1         # [win]
    - if NOT exist %LIBRARY_BIN%/bgen.dll exit 1         # [win]
    - if NOT exist %LIBRARY_LIB%/bgen_static.lib exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/bgen.h exit 1           # [win]
    - if NOT exist %LIBRARY_INC%/bgen/file.h exit 1      # [win]
    - if NOT exist %LIBRARY_INC%/bgen/depr.h exit 1      # [win]
    - if NOT exist %LIBRARY_INC%/bgen/str.h exit 1       # [win]
    - if NOT exist %LIBRARY_INC%/bgen/geno.h exit 1      # [win]
    - if NOT exist %LIBRARY_INC%/bgen/platform.h exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/bgen/meta.h exit 1      # [win]
    - if NOT exist %LIBRARY_INC%/bgen/api.h exit 1       # [win]


about:
  home: https://github.com/limix/bgen
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A BGEN file format reader'
  doc_url: https://bgen.readthedocs.io
  dev_url: https://github.com/limix/bgen

extra:
  recipe-maintainers:
    - horta
