{% set name = "bgen" %}
{% set version = "1.1.0" %}
{% set sha256 = "56d08c74ea6b4c5f8a264c6daf53ffef7e068d810420a5f7f885a5c20bce7a53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/bgen/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py27]
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - python  # [win]
    - toolchain
    - cmake
    - zstd
    - zlib   # [win]
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]
  run:
    - zstd
    - zlib   # [win]
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]

test:
  commands:
    - test -e $PREFIX/lib/libbgen.so                    # [linux]
    - test -e $PREFIX/lib/libbgen_static.a              # [unix]
    - test -e $PREFIX/include/bgen.h                    # [unix]
    - test -e $PREFIX/lib/libbgen.dylib                 # [osx]
    - if NOT exist %PREFIX%/lib/bgen.lib exit 1         # [win]
    - if NOT exist %PREFIX%/bin/bgen.dll exit 1         # [win]
    - if NOT exist %PREFIX%/lib/bgen_static.lib exit 1  # [win]
    - if NOT exist %PREFIX%/include/bgen.h exit 1       # [win]


about:
  home: https://github.com/limix/bgen
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A BGEN file format reader'
  doc_url: https://bgen.readthedocs.io
  dev_url: https://github.com/limix/bgen

extra:
  recipe-maintainers:
    - horta
