{% set name = "bgen" %}
{% set version = "4.0.1" %}
{% set sha256 = "42b92409652f1477244516251dca30ed749cef8384dfd7331bb840aff8c0eaf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/bgen/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
  host:
    - almosthere >=1.0.15
    - conda-build
    - zlib  # [win]
    - zstd
  run:
    - almosthere >=1.0.15
    - zlib  # [win]
    - zstd

test:
  commands:
    - test -e $PREFIX/lib/libbgen.so                      # [linux]
    - test -e $PREFIX/lib/libbgen.dylib                   # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME         # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME          # [osx]
    - if NOT exist %LIBRARY_LIB%/bgen.lib exit 1          # [win]
    - if NOT exist %LIBRARY_BIN%/bgen.dll exit 1          # [win]
    - if NOT exist %LIBRARY_INC%/bgen/bgen.h exit 1       # [win]
    - if NOT exist %LIBRARY_INC%/bgen/bstring.h exit 1    # [win]
    - if NOT exist %LIBRARY_INC%/bgen/export.h exit 1     # [win]
    - if NOT exist %LIBRARY_INC%/bgen/file.h exit 1       # [win]
    - if NOT exist %LIBRARY_INC%/bgen/genotype.h exit 1   # [win]
    - if NOT exist %LIBRARY_INC%/bgen/metafile.h exit 1   # [win]
    - if NOT exist %LIBRARY_INC%/bgen/partition.h exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/bgen/samples.h exit 1    # [win]
    - if NOT exist %LIBRARY_INC%/bgen/variant.h exit 1    # [win]

about:
  home: https://github.com/limix/bgen
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A BGEN file format reader
  doc_url: https://bgen.readthedocs.io
  dev_url: https://github.com/limix/bgen

extra:
  recipe-maintainers:
    - horta
