# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cAj6PWT2Ycc44HWQfNWvkIJUYKtJEh5/yyra7Ea6Nn9ocq+6ReRnoIx1V/3aHGHOiAICQAbFom5utRRQVjSAcbhbHROJd2+3Vxlb7zpwVou9CICUCCIWk0SCqFbozOS0Whcz24jtCOadO1z4kxTT2OCRLRTm7CH2rrwEzSAEEhcu7ncV+U4Ygw0z9rsiNt9cpiV9ZWk4ci7ylO7XRzAEbtrFpOkHK/i70dBllorAj6n3m5zQmMyHaxPpocq0b/bPGT/V4b36fJggXaj2Lx2evBdjDal9rWDx7vhFud8WOpsBDK5QWB8A15vzdnTevJNVIzHjp2wdD206a5XY3Xv5R96oaVzn9bLEv3l1aLhzlqD5t6tJWbvApu2HA31z/ziBkArKeFgp3uP8cc/qu5CP0KRUlc6eP5rCftLEi53aLE27KC8mLaj783ziAf39ygckUiow5jXY90FKIVXS8UEVsHq80J9VcNuzglOMVW+7CVCpfbae8OoWaJ1lwl5QOpd5Pxtg6F8YFdHNh0Gf1Y0N7iz8P6Hvk7BQ0JKOgDS5scx9/dvq0gHARx78wk+POeffpxJcL6ccWOAHm2AWAAPjKNtNVc8HbSZI8h3eQpDS9RbOjoR+Vc8F8X/V8FNSRi0zTse9AsddHyMWGiVhnipmVC+XYPHmhiIy80pwbf8bOnM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
