travis:
  secure:
    BINSTAR_TOKEN: pucKhTOX4OCrdtSrq2PspPDdfJeAocGD2ylutM2ymwb13iNBLczX49IExDqpNq0Pqvt20bq+YF7qkucjm6lw5KO0Ui4GoZh5gwnvKZH1bd2/fLK8KiAe9EfKzF906F5nwOe58bXIotx8WmC+fKubL78mhag6xOYDF+argwE8J3phl6wYznaAXfxjrPwJKczuTEto/XLnRYadNSg8WoYzjigANueUKg6LZVIQeh9PMCTxxpOxrNT+ZZ67PBHtrTs4QcS9gBjaRNxJuK7beDM1f8BHsG+93aolS0GR0bvenS5sI7R7nQqLjDIXCyNPM4o+3AO83tDO9WCm1PRvr5Q/iq3LJwpy0Hkp4n2KfSaZAOR/mtvGHkwg4NnJ/LDkwD92UaM5eyWyScBFC0ToLMN1KoZsTqvv20JayaCAdA0P6UCmBG9r6mu/xP/bfWmhVRwvr2EKv5g4kjrewOszvCyjaoLG2ey/sS6ndgioNkv0hAGII0bROP3T+fgqgac8t9ftnuLy5Yoei8U0XT3/KZl6aoHR5qy9EaJx4Eny9XtBTGMLiQIg9cgi8dIvZ5M/Xb9FUb5I5qixlNQMpGIjRUgSGKeSJ0LWYiW1bt+zVXCR29+NtPJBkLppNggOmnpezXNgvX6KycJMuhwt2KrUAzExZsHy4KvgvD8oazHTmRquLQk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
