travis:
  secure:
    BINSTAR_TOKEN: tHG9D0xt8zYMhIKh6PD0NStrphKoVXvfHJtx90ptWd893yW1RepItBKFT1IP/IV41MjIlvXA/jw19LB/2W9ZXMU7KYlINLFM9r0QtIQahourZMkXP3c2NSnZDzpt7NBNWIO7oPiSKF1byGFX2IZ88iL9I6IghcpxzAPUHzKnmk4eGPnMo5SU/W2nhrgfsHBtz2DCUBdHxYjt8a5mnO0nFk6jLAMcbJ33XhQAhEXr76aHW+6sr+YEpmuy3kxHEe26c/zop16u2HRKqiXd23p1XY18MHVyRMkBjaipgWXZa7AAlWvbLCU0ySwmtbljGLUo2uPLDB2qlTe+AEbTy+PRrwEZnQshrzT+GjLhkoJbpgJVg0RRjaQsab7Rt8Xq0XumcYpCG1wMKzQ16f/AaC8uB67rzB5QswhigmKOLJ2mHy5MrSy6+sH08IkiK2twNB+yj0PYPU7iButNF2QbyZzZGCCIn2DNvaUeWwBqY8FQzp7tfPgCYaznE8KypkwrojHxewO3X8TnWXIDN0exHfH/isvc1bA/JVHiJgSa3Y6R5khE/tYvs2PtzcHn7ljOJvHhRLVybo+gh2BrEV+6ThUgicnbl52h5J2nEMVt73mBUwEbePV+ztAAthZjnW1QHf1kMvCwchvlV+ABgrrx5acjmc4/VT+kBI/liafJjLNG+vQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
