travis:
  secure:
    BINSTAR_TOKEN: VZLKhf7Xxr0Wftk8dRX4sTQGwMSk0Cfglt8KCKU9Lh3lhoYSSyT57Y8QNEaZOxMODMYQNquNNna0LZf9Ty2nk6S75Ys535CdI2dttOE4Zp1nSKhKchxwZBAlgIlWR3egtMgwVUDblXE0TlhwFIQfHYwNMWg+A93sTLIRTOXagtNTDBTkyZ66VNMjxe/aSJ5No+hyuWx3N0iuGYGcQSoPn81b+L7Q+VHOcOEFNJaNXXjoPhlOx7mJwt02PyFdcLAbWJDMdsY9CnMX8ckjThEGv9/soqVFuQ8up9K9YYpIxWCRZSuQJkRowrRHdLj+xa/XIhlJB5x6JqKIxoSlqV+L1EitQRD8Yi9r9hQsYx0+UCKqAE0m7q6+fQBHCwxyZg7b9TWsYLyc1zfBRmQOVHo8ltX5DjGuLiq8FHzXQitzectIHrciB45L+Wnx+Hcy0bWWdiApCo7n0TPjs6YDEMCTfx7Qw4xxT+8JOJeGYfdyJQuc2pf2yBOEy9nd2rBmB8M48khSvT3+X6l9hRPwdCIWJOl2dJot6ItNumn8gikTk9x9WWGnThOvoTf9P5PaWGfkkkWe9c1UmeKukQZcRG70I4zgW5b90p2Z3WLEuZduuDCKZ5YO+5FgiWFaiGzcRQB6FgcmUDNB0CPQD+6r4srMz0b9ol2AA3m6nrUdL4n7v+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
