travis:
  secure:
    BINSTAR_TOKEN: cAj6PWT2Ycc44HWQfNWvkIJUYKtJEh5/yyra7Ea6Nn9ocq+6ReRnoIx1V/3aHGHOiAICQAbFom5utRRQVjSAcbhbHROJd2+3Vxlb7zpwVou9CICUCCIWk0SCqFbozOS0Whcz24jtCOadO1z4kxTT2OCRLRTm7CH2rrwEzSAEEhcu7ncV+U4Ygw0z9rsiNt9cpiV9ZWk4ci7ylO7XRzAEbtrFpOkHK/i70dBllorAj6n3m5zQmMyHaxPpocq0b/bPGT/V4b36fJggXaj2Lx2evBdjDal9rWDx7vhFud8WOpsBDK5QWB8A15vzdnTevJNVIzHjp2wdD206a5XY3Xv5R96oaVzn9bLEv3l1aLhzlqD5t6tJWbvApu2HA31z/ziBkArKeFgp3uP8cc/qu5CP0KRUlc6eP5rCftLEi53aLE27KC8mLaj783ziAf39ygckUiow5jXY90FKIVXS8UEVsHq80J9VcNuzglOMVW+7CVCpfbae8OoWaJ1lwl5QOpd5Pxtg6F8YFdHNh0Gf1Y0N7iz8P6Hvk7BQ0JKOgDS5scx9/dvq0gHARx78wk+POeffpxJcL6ccWOAHm2AWAAPjKNtNVc8HbSZI8h3eQpDS9RbOjoR+Vc8F8X/V8FNSRi0zTse9AsddHyMWGiVhnipmVC+XYPHmhiIy80pwbf8bOnM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
