travis:
  secure:
    BINSTAR_TOKEN: A9ooQcPvnltTmzszNiHMV4mIsqJ2ztl68Wk8H8H86aX9jeYqZCOHtWqEysmHxqE/1MtF5+5Fg1L8Y8EwN1AATAVON8HgqJDjzBI1652FJJaqd4Hi9nGpVEdC3P6w4aiAJ0XuXL3LKkakK0NY3wqjZWfM8uIiAE51NaKURHcORRpnH046wda0s5d0HIvoMgI/+KbTy2j7UBt5LCJPRAd0qryplZITEIcLZcX1dDtG60j5iye5P+QE/CXMlMHYdiROnFVLKAOZP076TbxvyOugre3+5e0bapJN5ND/Bj3w2w8pqAxUHYIEoiGqNygm6ej16bPo17YmbKFT12wRdxtwkv74K7hmmVP5ARvLcMgQwP+mI0ueF0kpwkzr0CxXRNt8anIo9PI/06y2kZItqCzFqUHwgsqGj98g3jNCa66OQifGRmKQAVxjaPECn6YR04cOycTaSP8Ko9IZUAW8XPW45a8slK2YMwo910PTMgtLqCs4oDqAe9tSnxj6P5mD9WegduZtSJtpf6cLDo5yWIeatPsVdWDnO4xSFGr2pOzkg4ABAkWpwelkqgr5gQbtPV09wak+4q2Ta+nEcp1cvgKxVGGbFkksdlu181+5xWLJ5d5mVg690ivzuDYh+jBnbhfdIkfAw2FUSKE8+6vECWWD6PlvPX/dTNKSzr5Tm+LaaiA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
